gas_adjustment = 1.5
fees = "100uxprt"

[server]
listen_addr = "0.0.0.0:7171"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[[deviation_thresholds]]
base = "OSMO"
threshold = "1.5"

[[deviation_thresholds]]
base = "ATOM"
threshold = "1.5"

[[currency_pairs]]
base = "ATOM"
providers = [
  "kraken",
  "binance",
  "coinbase",
  "huobi",
  "crypto",
]
quote = "USD"

[[currency_pairs]]
base = "USDC"
providers = [
  "osmosis",
  "kraken",
  "binance"
]
quote = "USD"

[[currency_pairs]]
base = "OSMO"
providers = [
  "kraken",
  "osmosis",
]
quote = "USD"

[account]
address = "persistence1pkkayn066msg6kn33wnl5srhdt3tnu2vv3k3tu"
chain_id = "test"
validator = "persistencevaloper1pkkayn066msg6kn33wnl5srhdt3tnu2v94kvz9"

[keyring]
# backend = "test"
# dir = "/tmp/trash/.persistenceCore"
mnemonic = "wage thunder live sense resemble foil apple course spin horse glass mansion midnight laundry acoustic rhythm loan scale talent push green direct brick please"

[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"
